config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  post 'home/redeem'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  before_create :create_uuid
  before_create :set_to_not_used

  private
  def create_uuid
    self.uuid = SecureRandom.uuid
  end

  def set_to_not_used
    self.used = false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def redeem
    voucher_uuid = params.permit(:voucher)[:voucher]
    subject = params.permit(:subject)[:subject]

    voucher = Voucher.find_by_uuid(voucher_uuid)

    if not voucher or voucher.used?
      flash[:error] = 'Please provide a valid voucher code.'
      return redirect_to root_path
    end

    voucher.used = true
    voucher.save!

    if subject == 'math_ct_5'
      cheatsheet_path = File.join(Rails.root, 'app','assets', 'pdfs', 'meme.jpg')
      send_file cheatsheet_path
    elsif subject == 'fce_ct_1'
      cheatsheet_path = File.join(Rails.root, 'app','assets', 'pdfs', 'fce CT 1.pdf')
      send_file cheatsheet_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Redeem Voucher</h1>
<p>Please enter your provided voucher code below:</p>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>

<%= form_tag(home_redeem_path, method: "post") do %>
  <%= label_tag(:voucher, "Voucher Code:") %>
  <%= text_field_tag(:voucher) %>

  <br>
  <%= radio_button_tag(:subject, "math_ct_5", checked: true) %>
  <%= label_tag(:subject_math_ct_5, "Math CT 5") %>
  <br>
  <%= radio_button_tag(:subject, "fce_ct_1") %>
  <%= label_tag(:subject_fce_ct_1, "FCE CT 1") %>
  <br>

  <%= submit_tag("Redeem") %>
<% end %>

app/views/home/redeem.html.erb
<h1>Home#redeem</h1>
<p>Find me in app/views/home/redeem.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bgssnotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>